# Generated by Django 5.2.5 on 2025-09-03 11:59

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('sId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('gender', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('passout_year', models.SmallIntegerField()),
                ('university', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=100)),
                ('tools', models.CharField(max_length=100)),
                ('marks10', models.DecimalField(decimal_places=2, max_digits=4)),
                ('marks12', models.DecimalField(decimal_places=2, max_digits=4)),
                ('internship', models.BooleanField(default=False)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('profile', models.CharField(blank=True, max_length=50, null=True)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField()),
                ('job_location', models.CharField(choices=[('PAN INDIA', 'PAN INDIA'), ('Other', 'Other')], default='PAN INDIA', max_length=10)),
                ('other_location', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='placement.student')),
            ],
        ),
    ]
