# Generated by Django 5.2.5 on 2025-09-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='specialization',
            field=models.CharField(default='xxxx', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='marks10',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='marks12',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
