# Generated by Django 5.2.5 on 2025-11-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_alter_applicationstatus_round1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
