# Generated by Django 5.2.5 on 2025-09-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_student_specialization_alter_studentprofile_marks10_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='project_name',
            new_name='board10',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='start_date',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='board12',
            field=models.CharField(default='xxxx', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='duration',
            field=models.CharField(blank=True, choices=[('45 days', '45 days'), ('90 days', '90 days'), ('3-6 months', '3-6 months'), ('Currently Working', 'Currently Working')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='project_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills_gained',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills_learned',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='stipend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
