# Generated by Django 5.2.5 on 2025-12-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_student_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
