# Generated by Django 5.2.5 on 2025-09-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_rename_project_name_studentprofile_board10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='post_graduation_college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='post_graduation_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
