# Generated by Django 5.2.5 on 2025-12-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_job_active_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='verification_status',
            new_name='verification_status_mail',
        ),
        migrations.AddField(
            model_name='student',
            name='verification_status_phone',
            field=models.BooleanField(default=False),
        ),
    ]
