# Generated by Django 5.2.5 on 2025-09-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_studentprofile_graduation_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
