# Generated by Django 5.2.5 on 2025-09-09 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_studentprofile_github_studentprofile_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('placement_type', models.CharField(max_length=50)),
                ('job_stipend', models.CharField(max_length=50)),
                ('package', models.CharField(max_length=50)),
                ('eligiblity_batch', models.CharField(max_length=50)),
                ('eligiblity_10_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eligiblity_12_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eligiblity_college_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eligiblity_others', models.TextField()),
                ('application_deadline', models.DateField()),
                ('question1', models.CharField(blank=True, max_length=200, null=True)),
                ('question2', models.CharField(blank=True, max_length=200, null=True)),
                ('question3', models.CharField(blank=True, max_length=200, null=True)),
                ('question4', models.CharField(blank=True, max_length=200, null=True)),
                ('question5', models.CharField(blank=True, max_length=200, null=True)),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
