# Generated by Django 5.2.5 on 2025-09-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0006_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobs',
            new_name='job',
        ),
    ]
