# Generated by Django 5.2.5 on 2025-09-12 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0007_rename_jobs_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apply_date', models.DateField(auto_now_add=True)),
                ('answer1', models.TextField(blank=True, null=True)),
                ('answer2', models.TextField(blank=True, null=True)),
                ('answer3', models.TextField(blank=True, null=True)),
                ('answer4', models.TextField(blank=True, null=True)),
                ('answer5', models.TextField(blank=True, null=True)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.job')),
                ('sId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement.student')),
            ],
        ),
    ]
