# Generated by Django 5.2.5 on 2025-09-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0008_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sId',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
