# Generated by Django 5.2.5 on 2025-09-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0009_alter_student_sid_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
