# Generated by Django 5.2.5 on 2025-09-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0011_job_question10_job_question6_job_question7_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='internship',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='project',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3),
        ),
    ]
