# Generated by Django 5.2.5 on 2025-09-22 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0015_alter_studentprofile_internship_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='student',
            new_name='sId',
        ),
    ]
