# Generated by Django 5.2.5 on 2025-09-22 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0016_rename_student_studentprofile_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='sId',
            new_name='student',
        ),
    ]
