# Generated by Django 5.2.5 on 2025-10-06 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0018_job_type1_job_type10_job_type2_job_type3_job_type4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='city',
            new_name='university_city',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='state',
            new_name='university_state',
        ),
    ]
