# Generated by Django 5.2.5 on 2025-10-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0020_studentprofile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(default='xxxx', upload_to='resumes/'),
            preserve_default=False,
        ),
    ]
